name: Deploy to kir951
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

env:
  test_name: my-Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOY_KEY_KIR951 }}
          host: ${{ secrets.DEPLOY_HOST_KIR951 }}
          username: ${{ secrets.DEPLOY_USER_KIR951 }}
          port: ${{ secrets.PORT_KAGOYA }}
#          script: |
#            cd /public_html/test_yamauchi/
#            git pull origin main
          script: |
            whoami
            ls -al
