name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY_KIR951 }}
          known_hosts: ${{ secrets.DEPLOY_HOST_KIR951 }}
      - name: rsync deploy
        run: rsync -vcrlp -e "ssh -p ${{ secrets.PORT_KAGOYA }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./ ${{ secrets.DEPLOY_USER_KIR951 }}@${{ secrets.DEPLOY_HOST_KIR951 }}:public_html/test_yamauchi/*/*/


