name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY_KIR951 }}
          known_hosts: ${{ secrets.DEPLOY_HOST_KIR951 }}
      - name: rsync deploy
        run: rsync -vrlp -e "ssh -p 10022 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./ kir951032@o5044-691.kagoya.net:/

          echo Add other actions to build,
          echo test, and deploy your project.




#name: Deploy to kir951
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install SSH Key for Deploy
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.DEPLOY_KEY_KIR951 }}
#          known_hosts: ${{ secrets.DEPLOY_HOST_KIR951 }}
#      - name: rsync deploy
#        run: rsync -vrlp -e "ssh -p ${{ secrets.PORT_KAGOYA }} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./ ${{ secrets.DEPLOY_USER_KIR951 }}@${{ secrets.DEPLOY_HOST_KIR951 }}:/public_html/test_yamauchi/