name: Deploy to kir951
on:
  push:
    branches: main

env:
  test_name: my-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOY_KEY_SERVER_KIR951 }}
          username: ${{ secrets.DEPLOY_USER_SERVER_KIR951 }}
          host: ${{ secrets.DEPLOY_HOST_SERVER_KIR951 }}
          port: ${{ secrets.DEPLOY_PORT_SERVER }}
          script: |
            cd /public_html/test_yamauchi/
            git pull