name: Deploy to kir951
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: ssh
        env:
          SECRET_KEY: ${{ secrets.DEPLOY_KEY_KIR951 }}
          USER: ${{ secrets.DEPLOY_USER_KIR951 }}
          HOST: ${{ secrets.DEPLOY_HOST_KIR951 }}
        run: | 
            echo "$SECRET_KEY" > secret_key
            chmod 600 secret_key
            ssh -p ${{ secrets.PORT_KAGOYA }} sync ${DEPLOY_USER_KIR951}@${DEPLOY_HOST_KIR951} -i secret_key "cd ./public_html/ && sh ./.github/workflows/deploy.sh"
